# Why NumPy?
 - Less bytes of memory to read (faster)
 - No type-checking when iterating (faster)
 - Contiguous memory
 - Multiplaction of arrays (lists)
 
### Load NumPy (pip install if necessary)

In [2]:
import numpy as np

### Basics

In [73]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
c = np.array([[14, 36], [7, 99], [42,1]], dtype='int16')
print(c)

[[14 36]
 [ 7 99]
 [42  1]]


In [7]:
# Get Dimensions
a.ndim

1

In [14]:
c.ndim

2

In [8]:
# Get Shape
b.shape

(2, 3)

In [15]:
c.shape

(3, 2)

In [9]:
# Get Type
a.dtype

dtype('int32')

In [16]:
c.dtype

dtype('int16')

In [31]:
# Get Size
a.itemsize

4

In [17]:
c.itemsize

2

In [29]:
# Get total size
a.nbytes

12

In [18]:
c.nbytes

12

In [35]:
# Get number of elements
a.size

3

In [19]:
c.size

6

### Accessing/Editing Specific Elements, Rows, Columns, etc.

In [25]:
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],
             [15,16,17,18,19,20,21,], [22,23,24,25,26,27,28]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]


In [26]:
# Get a specific element [r, c]
d[1, 5]

13

In [32]:
# Can also use negative index
d[0, -1]

7

In [29]:
# Get a specific row 
d[2, :]

array([15, 16, 17, 18, 19, 20, 21])

In [31]:
# Get a specific column
d[:, 0]

array([ 1,  8, 15, 22])

In [33]:
# Getting a little more fancy [startindex:endindex:stepsize]
d[0, 1:-1:2]

array([2, 4, 6])

In [36]:
e = np.copy(d)
e[-1,-1] = 777
print(e)

e[:,5] = [0,0,0,0]
print(e)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27 777]]
[[  1   2   3   4   5   0   7]
 [  8   9  10  11  12   0  14]
 [ 15  16  17  18  19   0  21]
 [ 22  23  24  25  26   0 777]]


##### 3-D Example

In [38]:
f = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (work outside in: array, row, column)
f[1,1,0]

7

In [45]:
# replace 
f[0,:,:] = [[42, 99],[13, 1]]

In [46]:
f

array([[[42, 99],
        [13,  1]],

       [[ 5,  6],
        [ 7,  8]]])

### Initializing Different Types of Arrays

In [47]:
# All 0s matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
# All 1s matrix
np.ones((4,3,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [53]:
# All (any number) matrix
np.full((5,5), 42)

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

In [54]:
# Any other number (full_like)
np.full_like(b, 6)

array([[6., 6., 6.],
       [6., 6., 6.]])

In [56]:
# Random decimal numbers
# Decimals are between 0 and 1
np.random.rand(6,2)

array([[0.11602008, 0.20667829],
       [0.0241556 , 0.57780451],
       [0.18584222, 0.90851457],
       [0.09460331, 0.72466277],
       [0.43586977, 0.38427853],
       [0.89810472, 0.91404981]])

In [58]:
# Random integer values
# First is int range which is inclusive, followed by array size
np.random.randint(-10,10, size=(3,4))

array([[  4, -10,   3,   3],
       [  7,  -5, -10,   9],
       [  7,  -6,   9,  -2]])

In [59]:
# The identity matrix
# Full of only 0s and 1s
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [62]:
# Repeat an array
g = np.array([[3,6,9]])
r1 = np.repeat(g,3, axis=0)
print(r1)

print()

r2 = np.repeat(g,3, axis=1)
print(r2)

[[3 6 9]
 [3 6 9]
 [3 6 9]]

[[3 3 3 6 6 6 9 9 9]]


In [64]:
uno = np.ones((5,5))
print(uno)

print()

zero = np.zeros((3,3))
zero[1,1] = 9
print(zero)

print()

uno[1:-1,1:-1] = zero
print(uno)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [67]:
h = np.array([24,88,253])

# make sure to use  <array>.copy() or np.copy(<array)
h2 = a.copy()
h2[0] = 101
print(h)

print()

print(h2)

[ 24  88 253]

[101  88 253]


### Mathematics
##### Does not effect array unless it is stored.

In [77]:
i = np.array([1,2,3,4])
print(i)

[1 2 3 4]


In [78]:
i + 2

array([3, 4, 5, 6])

In [79]:
i - 2

array([-1,  0,  1,  2])

In [80]:
i * 2

array([2, 4, 6, 8])

In [81]:
i / 2

array([0.5, 1. , 1.5, 2. ])

In [82]:
j = np.array([1,0,1,0])
i + j

array([2, 2, 4, 4])

In [83]:
i ** 2

array([ 1,  4,  9, 16])

In [87]:
# Take trig functions
print("sin:", np.sin(i))
print("cos:", np.cos(i))
print("tan:", np.tan(i))

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128]


#### For more: https://docs.scipy.org/doc/numpy/reference/routines.math.html

##### Linear Algebra

In [90]:
# Matrix multiplication
k = np.ones((2,3))
print(k)

l = np.full((3,2), 2)
print(l)

np.matmul(k,l)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [91]:
# Find the determinant
m = np.identity(3)
np.linalg.det(m)

1.0

##### Reference: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc.

##### Statistics

In [92]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
np.min(stats)

1

In [94]:
np.max(stats, axis=1)

array([3, 6])

In [143]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [100]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print()

after = before.reshape((4,2))
print(after)
print()

after2 = before.reshape((8,1))
print(after2)
print()

after3 = before.reshape((2,2,2))
print(after3)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [102]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

v3 = np.vstack([v1,v2])
v3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

h3 = np.hstack((h1,h2))
h3

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [105]:
data = np.genfromtxt('data.txt', delimiter=',')
data = data.astype('int32')
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [108]:
bool1 = data > 50
print(bool1)

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


In [110]:
values1 = data[data > 50]
print(values1)

[196  75 766  75  55 999  78  76  88]


In [112]:
(~((data > 50) & (data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
(~((filedata > 50) & (filedata < 100)))